title = "Siobhán Keating, Technical Writer"
baseURL = "https://keatingsc.github.io"
languageCode = "en-us"
publishDir = "public"

# The name of this wonderful theme ;-).
theme = "anatole"
[[menu.main]]
name = "Home"
identifier = "home"
weight = 100
url = "/"

[[menu.main]]
name = "About me"
weight = 200
identifier = "about"
url = "/about/Siobhan-Keating-Technical-Writer"

[[menu.main]]
name = "Contact"
weight = 300
identifier = "contact"
url = "/contact/contact"

[params]
  # The path to your "favicon". This should be a square (at least 32px x 32px) png-file.
  title = "SIOBHÁN KEATING"
  author = "Siobhán Keating"
  profilePicture = "images/profileSK.jpg"

# The name of this wonderful theme ;-).
theme = "anatole"

# This is a "one page"-website, so we do not need these kinds of pages...
disableKinds = ["section", "taxonomy", "term", "RSS", "robotsTXT"]

  # The path to your "favicon". This should be a square (at least 32px x 32px) png-file.
  favicon = "favicons/"

  site_logo = ""
  description = "A summary of what technical writing means to me."
  ## Social links
  # use 'fab' when brand icons, use 'fas' when standard solid icons.
  [[params.socialIcons]]
  icon = "fab fa-linkedin"
  title = "Linkedin"
  url = "https://www.linkedin.com/in/siobhan-keating2017/"

  [[params.socialIcons]]
  icon = "fab fa-github"
  title = "GitHub"
  url = "https://github.com/keatingsc/technical-writing"

  [[params.socialIcons]]
  icon = "fas fa-envelope"
  title = "e-mail"
  url = "mailto:siobhan.c.keating@gmail.com"
  # footer
  # A "copyright"-line to be added at the bottom of the page.
  # Hint: Markdown is supported in here as well. So you may e.g. add a link to your legal imprint-page.
  copyright = "© Siobhán Keating"
  copystart = "2000"
  author = "Siobhán Keating"

  # choose a background color from any on this page: http://tachyons.io/docs/themes/skins/ and preface it with "bg-"
  background_color_class = "bg-blue"
  featured_image = "/images/logoSK.png"
  recent_posts_number = 2
