title = "Siobhán Keating, Technical Writer"
baseURL = "https://example.com"
languageCode = "en-us"
<<<<<<< HEAD

# The name of this wonderful theme ;-).
theme = "hugo-scroll"

# This is a "one page"-website, so we do not need these kinds of pages...
disableKinds = ["section", "taxonomy", "term", "RSS", "robotsTXT"]

[params]
  # The path to your "favicon". This should be a square (at least 32px x 32px) png-file.
  favicon = "images/favicon.png"
  
  site_logo = ""
  description = "A summary of what technical writing means to me."
  # footer
  # A "copyright"-line to be added at the bottom of the page.
  # Hint: Markdown is supported in here as well. So you may e.g. add a link to your legal imprint-page.
  copyright = "© Siobhán Keating"
  copystart = "2000"
  author = "Siobhán Keating"
  # Repository configuration (URLs for in-page links to opening issues and suggesting changes)
  github_repo = "https://github.com/keatingsc/technical-writing"
  linkedin = "https://www.linkedin.com/in/siobhan-keating2017/"
  mastodon = ""
  slack = ""
  stackoverflow = ""
  rss = ""
  # choose a background color from any on this page: http://tachyons.io/docs/themes/skins/ and preface it with "bg-"
  background_color_class = "bg-blue"
  featured_image = "/images/logoSK.png"
  recent_posts_number = 2
